### ISSUE TITLE
请问有实现webview后面查看评论和添加评价的功能

### ISSUE THREAD

**Issue by 03128crz** [lookingstars/meituan#4]

**Comment by lookingstars** [comment]
有查看评论的接口，但是没做。只做get请求，不做post请求，添加评论的功能不能做，评论的话去官方的app里评论吧。

**Comment by 03128crz** [comment]
呵呵，其实我是想知道其它人做这块的具体思路是怎么样的：
上面是个webview，滚动到最下面加载最新评价或输入评价后也会加载
