### ISSUE TITLE
[!] Invalid `Podfile` file: Invalid char `\x7F' in expression

### ISSUE THREAD

**Issue by leewi9** [lookingstars/meituan#6]
你好，这个是什么问题？

```
13:53:21 leewi9 /Volumes/BX200/DEV/TEST/meituan-master  第6条 $ pod install --no-repo-update

[!] Invalid `Podfile` file: Invalid char `\x7F' in expression
/Volumes/BX200/DEV/TEST/meituan-master/Podfile:10: Invalid char `\x7F' in expression. Updating CocoaPods might fix the issue.

 #  from /Volumes/BX200/DEV/TEST/meituan-master/Podfile:9
 #  -------------------------------------------
 #  pod 'UMengAnalytics'
 >  pod 'AMap3DMap'
 #  pod 'AMapSearch'
 #  -------------------------------------------
```

**Comment by shmily1119** [comment]
应该是使用cocoa pods导入的第三方库出现了问题  看看第三方库的名字或者其他的对不对

**Comment by shmily1119** [comment]
用cocoapods导入第三方的时候出错了吧  是不是导入的第三方库不对

**Comment by leewi9** [comment]
找到原因了，把其中两个乱码删除就可以了

```
 >  pod �'AMap3DMap'
 #  pod �'AMapSearch'
```

**Comment by shmily1119** [comment]
能不能问下你是哪位 怎么知道我的邮箱的在 2016年3月23日，下午2:18，leewi9 notifications@github.com 写道：找到原因了，把其中两个乱码删除就可以了

**Comment by leewi9** [comment]
这就是github的issue功能 我提issue 你就会收到邮件 应该是你的登记邮箱地址 我看不到 系统转发

**Comment by luojun1** [comment]
[!] Invalid `Podfile` file: Invalid char `\x7F' in expression
/Users/Developer/Desktop/lj/boomsense/study/demo/swiftMeituan/swiftmeituan/Podfile:10: Invalid char`\x7F' in expression.

 #  from /Users/Developer/Desktop/lj/boomsense/study/demo/swiftMeituan/swiftmeituan/Podfile:9
 #  -------------------------------------------
 #  pod 'UMengAnalytics'

>  pod 'AMap3DMap'
>  #  pod 'AMapSearch'
>  #  -------------------------------------------
> 请问这事啥原因？？google／stackOverfloaw都没有找到解决办法？？？
