### ISSUE TITLE
cocoa pods更新，请修改Podfile文件

### ISSUE THREAD

**Issue by sunhdmn** [lookingstars/meituan#8]
platform :ios, '7.0'
use_frameworks!
inhibit_all_warnings!
target ‘meituan’
pod 'AFNetworking', '~>2.0'
pod 'SDWebImage', '3.7.2'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'MJRefresh',  '1.4.5'
pod 'MJExtension',  '1.2.1'
pod 'SVProgressHUD',  '1.1.3'
pod 'UMengAnalytics', '3.4.6'
pod 'AMap3DMap', '2.5.0'
pod 'AMapSearch',  '2.5.0'
pod 'AFNetworkActivityLogger'

**Comment by lookingstars** [comment]
@sunhdmn   thx~
